### This file is to test your routes easily, download the REST Client extension
### on VS CODE

### Default values for all games
GET http://localhost:3001/api/games

### Page 1 Size 2
GET http://localhost:3001/api/games?page=1&size=2

### Page 2 Size 2
GET http://localhost:3001/api/games?page=2&size=2

### Get the count of games 
GET http://localhost:3001/api/games/count

### Get games filter by name
GET http://localhost:3001/api/games?page=1&name=zelda&platform=Wii&platform=DS

### Get the count of games with filter
GET http://localhost:3001/api/games/count?name=zelda&platform=Wii

### Get all the users
GET http://localhost:3001/api/users
### Post a review 
POST http://localhost:3001/api/games/62193d7e1533a971c15a7bc9?email=rodddddd@email.com&rating=2&text=gamebad!!!

### Get a profile picture
GET http://localhost:3001/api/user/pfp?email=jwu12322@gmail.com

### Delete an user
DELETE http://localhost:3001/api/users/delete/62192e8d31881057a8dba25e

### Update admin permissions
PUT http://localhost:3001/api/users/update/6224f270f052985a6a7d2820

### Get specific user
GET http://localhost:3001/api/user/621ac4e04390cb547c00fe7f